version: '3'
services:
  mysql-symphony-api:
    image: postgres:12-alpine
    container_name: postgres-symphony-api
    volumes:
      - ./script/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    restart: unless-stopped